name: Deploy documentation

on:
  release:
    types: [ published ]
  push:
    branches:
      - master

jobs:

  build_deploy:
    name: Build and deploy documentation

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Define version name
        run: |
          if [ ${{ startsWith(github.ref_name, 'dev') }} = true ]; then
            echo "1st if"
            echo "VERSION_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [ ${{ github.event.release.tag_name != '' }} = true ]; then
            echo "2nd if"
            echo "VERSION_NAME=version/${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "else..."
            echo "VERSION_NAME=latest" >> $GITHUB_ENV
          fi
      - name: Now end is available
        run: |
          echo "Version to build: ${{ env.VERSION_NAME }}"
