name: Deploy documentation

on:
  release:
    types: [ published ]
  push:
    branches:
      - master

jobs:

  build_deploy:
    name: Build and deploy documentation

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: if [ ${{ github.event.release.tag_name == '' }} = true ]; then
          echo "VERSION_NAME=version/${{ github.event.release.tag_name }}"
